### ISSUE TITLE
pre-check

### ISSUE THREAD

**Issue by JohnHarald** [azureskydiver/MatchChallenge#5]
You may recall the good-bad comparison I posted in previous Issue [here](https://github.com/azureskydiver/MatchChallenge/issues/3#issuecomment-1001282984), where most methods except KMP have a strong bias towards matching good input.

I've been thinking about ways to help them with the bad inputs. One way (only way?) to do it is to introduce a Precheck to figure out if it could be viable to proceed at all. 

I did this and checked only two letters for match then did a Mixed test for all PartsMatcher methods, with and without the precheck. Substring+SpanSlice and Offset+Modulo already does this in their own way, so they can be ignored.
Mainly only two methods benefit from the precheck: Split and Replace. Performance for bad input gets a little better (Mixed test close to SpanSlice) and memory usage drops **a lot**. Here's the stats: [precheck.txt](https://github.com/azureskydiver/MatchChallenge/files/7786591/precheck.txt)

Would you approve such modification? It would make them less "pure", but not intervene much. 
I would add a virutal Precheck method to abstract PartsMatcher, and let derived classes decide if they want to use it.
```
protected virtual bool PreCheck(PartData data)
{
    var span = data.Input.AsSpan();
    return span[0] == span[data.PartLength];
}
```

**Comment by azureskydiver** [comment]
I think the prechecks idea is a good idea. Yes, it may skew the results, but it would also show what the expected production type code would look like.

**Comment by JohnHarald** [comment]
Added to Main, closing this issue.
