### ISSUE TITLE
result when no match

### ISSUE THREAD

**Issue by JohnHarald** [azureskydiver/MatchChallenge#7]
From where this started the methods returned "-1" when no match, which can also be a valid match for repeating string - isn't is about time this was changed to return `null` instead?

**Comment by azureskydiver** [comment]
Probably empty string would be more appropriate to keep the C# null police happy.

**Comment by JohnHarald** [comment]
"" compares as equal to null so that should be ok. Either that or return `string?`

**Comment by azureskydiver** [comment]
I'm so very tempted to also declare a `const string NoMatch`, but I just don't know where to stick it in. Gotta read up on C# 10 to see if the constant can be in the interface.

**Comment by azureskydiver** [comment]
C# 7.0 added the ability to define constants in interfaces. Nice!

**Comment by JohnHarald** [comment]
Yes, works fine.
