### ISSUE TITLE
Regex matcher(s ?) can't handle input string with Regex special characters

### ISSUE THREAD

**Issue by azureskydiver** [azureskydiver/MatchChallenge#8]
Going to need to ad pre-processing steps in the Regex matcher(s ?) to escape any special characters if part of the input string is used for any pattern matching.

I suspect that the PureRegexMatcher is going to be safe, but that the RegexMatcher will need some help.

**Comment by JohnHarald** [comment]
I have a fix ready with Regex.Escape for RegexMatcher. Push that to Main?
Including const NoMatch in IMatcher

PureRegexMatcher has no input in pattern expression so it is safe.
